import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout is a functional component that serves as the root layout for
 * all pages in the Next.js application. It takes in a single prop, `children`,
 * which is the content of the page.
 *
 * The component returns an HTML element with the `lang` attribute set to "en"
 * and a `body` element with the `className` attribute set to a combination of
 * the `className` property of the `inter` object and the strings "w-full" and
 * "h-[100vh]". The `children` prop is rendered as the content of the `body`
 * element.
 *
 * @param {Object} props - An object containing the `children` prop.
 * @param {React.ReactNode} props.children - The content of the page.
 * @return {JSX.Element} The root layout for the Next.js application.
 */
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  // Return an HTML element with the `lang` attribute set to "en" and a `body`
  // element with the `className` attribute set to a combination of the `className`
  // property of the `inter` object". The
  // `children` prop is rendered as the content of the `body` element.
  return (
    <html lang="en">
      <body className={`${inter.className} h-[90vh]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
